# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Александр Снаговский
email: asnagovskiy@ukr.net
description: > # this means to ignore newlines until "baseurl:"
  «Фотография — это выражение впечатления. Если прекрасное не жило бы в нас, как бы мы могли узнать его?»
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

menu:
  - url: /
    name: Главная
  - url: '#'
    name: Портфолио
    submenu:
      - url: /gallery/portraits
        name: Портреты
      - url: /gallery/nature
        name: Природа
      - url: /gallery/animals
        name: Животные
  - url: https://snagovskiy.tumblr.com
    name: Блог


facebook: asnagovskiy
googleplus: +АлександрСнаговский
instagram: snagoff
telegram: snagoff

# Build settings
markdown: kramdown
timezone: Europe/Kiev
google_analytics: UA-27551461-4
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - sass
  - prepros-6.config
