title: Александр Снаговский
email: asnagovskiy@ukr.net
description: > # this means to ignore newlines until "baseurl:"
  «Фотография — это выражение впечатления. Если прекрасное не жило бы в нас, как бы мы могли узнать его?»
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-27551461-4
lang: ru
timezone: Europe/Kiev

#Main menu
menu:
  - url: /
    name: Главная
  - url: '#'
    name: Портфолио
    submenu:
      - url: /gallery/portraits
        name: Портреты
      - url: /gallery/nature
        name: Природа
      - url: /gallery/animals
        name: Животные

#Social links
facebook: asnagovskiy
googleplus: +АлександрСнаговский
instagram: snagoff
telegram: snagoff

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - sass
sass:
  style: compressed
